name: GDFold2
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.8
  - numpy
  - pandas
  - biopython
  - biopandas
  - tqdm
  - numba
  - h5py
  - scipy
  - pytorch=1.12.1
  - pyg
  - pip
  - pip:
      - https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_cluster-1.6.0%2Bpt112cu113-cp38-cp38-linux_x86_64.whl
      - https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_scatter-2.1.0%2Bpt112cu113-cp38-cp38-linux_x86_64.whl